# String for demonstration
sample_str = "Hello, Python! Welcome to the world of programming."


print("1. capitalize():", sample_str.capitalize())
print("2. casefold():", sample_str.casefold())
print("3. center(50, '*'):", sample_str.center(50, '*'))
print("4. count('o'):", sample_str.count('o'))
print("5. encode('utf-8'):", sample_str.encode('utf-8'))
print("6. endswith('ing.'):", sample_str.endswith('ing.'))
sample_str_with_tabs = "Hello\tWorld"
print("7. expandtabs(4):", sample_str_with_tabs.expandtabs(4))
print("8. find('Python'):", sample_str.find('Python'))
print("9. format():", "Hello, {}!".format("World"))
print("10. format_map():", "{name} is {age} years old.".format_map({'name': 'John', 'age': 25}))
print("11. index('Python'):", sample_str.index('Python'))
print("12. isalnum():", "Python3".isalnum())
print("13. isalpha():", "Python".isalpha())
print("14. isdecimal():", "12345".isdecimal())
print("15. isdigit():", "12345".isdigit())
print("16. isidentifier():", "Python3".isidentifier())
print("17. islower():", "python".islower())
print("18. isnumeric():", "12345".isnumeric())
print("19. isprintable():", "Hello, World!".isprintable())
print("20. isspace():", "   ".isspace())
print("21. istitle():", "Hello, World!".istitle())
print("22. isupper():", "HELLO".isupper())
print("23. join():", "-".join(["Python", "is", "fun"]))
print("24. ljust(20, '*'):", "Python".ljust(20, '*'))
print("25. lower():", sample_str.lower())
print("26. lstrip('He'):", sample_str.lstrip('He'))
print("27. partition('Python'):", sample_str.partition('Python'))
print("28. replace('Python', 'Java'):", sample_str.replace('Python', 'Java'))
print("29. rfind('o'):", sample_str.rfind('o'))
print("30. rindex('o'):", sample_str.rindex('o'))
print("31. rjust(20, '*'):", "Python".rjust(20, '*'))
